<?php
$title = 'Delete';
$this->headTitle($title);
?>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <section class="panel">
            <header class="panel-heading">
                <?=$title?>
            </header>
            <div class="panel-body">

                <p>Are you sure that you want to <code>DELETE</code> <?=$user->getEmail()?></p>
                <form action="" method="post">
                    <input class="btn btn-primary" type="submit" name="delete" value="Yes" />
                    <input class="btn btn-warning"  type="submit" name="delete" value="No" />
                    <br /><br />
                </form>
            </div>
        </section>
    </div>
</div>