<section class="panel">
    <header class="panel-heading">
        Users
    </header>
    <div class="panel-body">
    	<table class="table table-condensed">
        	<tr><td width="10"></td><td>Email</td><td>Type</td><td>Last Login</td></tr>
            <?php $ctr = 1; foreach($users as $entry) : ?>
           	<tr><td><span class="label label-default"><?=$ctr?></span></td><td><?=$entry->getEmail()?></td>
            <td><?php foreach($entry->getRoles() as $v) : ?>
            	<span class="label label-default"><?=$v->getRoleId()?></span>
            <?php endforeach; ?>
            </td>
            <td><?=$entry->getLastLogin()?$entry->getLastLogin()->format('F j, Y H:ia'):''?></td></tr>
            <?php $ctr++; endforeach; ?>
        </table>
    </div>
</section>